const Strings = {
  notifications: {
    notEnoughResources: 'Not enough resources to purchase this improvement'
  },
  common: {
    shop: 'Shop',
    fullyUpgraded: 'This improvement is fully upgraded'
  },
  improvements: {
    treasury: {
      treasury: 'Treasury',
      upgrade: 'Upgrade Treasury',
      upgrade1: 'Upgrade Treasury (lvl 1)',
      upgrade2: 'Upgrade Treasury (lvl 2)',
      upgrade3: 'Upgrade Treasury (lvl 3)',
      upgrade4: 'Upgrade Treasury (lvl 4)',
      upgrade5: 'Upgrade Treasury (lvl 5)',
    },
    armory: {
      armory: 'Armory',
      upgrade: 'Upgrade Armory',
      upgrade1: 'Upgrade Armory (lvl 1)',
      upgrade2: 'Upgrade Armory (lvl 2)',
      upgrade3: 'Upgrade Armory (lvl 3)',
      upgrade4: 'Upgrade Armory (lvl 4)',
      upgrade5: 'Upgrade Armory (lvl 5)',
    },
    cellar: {
      cellar: 'Cellar',
      upgrade: 'Upgrade Cellar',
      upgrade1: 'Upgrade Cellar (lvl 1)',
      upgrade2: 'Upgrade Cellar (lvl 2)',
      upgrade3: 'Upgrade Cellar (lvl 3)',
      upgrade4: 'Upgrade Cellar (lvl 4)',
      upgrade5: 'Upgrade Cellar (lvl 5)',
    },
    theives: {
      theives: 'Theives Guild',
      upgrade: 'Upgrade Theives Guild',
      upgrade1: 'Upgrade Theives Guild (lvl 1)',
      upgrade2: 'Upgrade Theives Guild (lvl 2)',
      upgrade3: 'Upgrade Theives Guild (lvl 3)',
      upgrade4: 'Upgrade Theives Guild (lvl 4)',
      upgrade5: 'Upgrade Theives Guild (lvl 5)',
    },
    science: {
      science: 'Science Lab',
      upgrade: 'Upgrade Science Lab',
      upgrade1: 'Upgrade Science Lab (lvl 1)',
      upgrade2: 'Upgrade Science Lab (lvl 2)',
      upgrade3: 'Upgrade Science Lab (lvl 3)',
      upgrade4: 'Upgrade Science Lab (lvl 4)',
      upgrade5: 'Upgrade Science Lab (lvl 5)',
    }
  },
  weapons: {
    goldDagger: 'Gold Dagger',
    goldDaggerDesc: 'A dagger that increases gold found by 10%',
    goldSaber: 'Gold Saber',
    goldSaberDesc: 'A moderate saber that increases gold found by 20%',
    ironShortSword: 'Iron Short Sword',
    ironShortSwordDesc: 'A basic yet effective short sword',
    brittleRapier: 'Brittle Rapier',
    brittleRapierDesc: 'A weapon that exchanged high crit chance with brittleness. May break.',
    blunderbuss: 'Blunderbuss',
    blunderbussDesc: 'A powerful gun that causes splash damage',
    whip: 'Whip',
    whipDesc: 'A weapon with high crit chance',
    broadSword: 'Broad Sword',
    broadSwordDesc: 'A powerful basic weapon',
  },
  armor: {
    goldVest: 'Gold Vest',
    goldVestDesc: 'A vest with low defense but increases gold found by 10%',
    goldJacket: 'Gold Jacket',
    goldJacketDesc: 'A jacket with moderate defense but increases gold found by 20%',
    leatherArmor: 'Leather Armor',
    leatherArmorDesc: 'Basic armor made of leather',
    leatherJacket: 'Leather Jacket',
    leatherJacketDesc: 'A tough jacket made of leather. Stylish and effective',
    clockworkSuit: 'Clockwork Suit',
    clockworkSuitDesc: 'A suit brimming with doodads. Increases SCI ATK and DEF',
    mechanicalJumper: 'Mechanical Jumper',
    mechanicalJumperDesc: 'A jumpsuit with tons of nifty gadgets. Increases SCI ATK and DEF',
    clockworkArmor: 'Clockwork Armor',
    clockworkArmorDesc: 'A suit of armor with a clockwork core. Increases SCI ATK and DEF',
    chainVest: 'Chain Vest',
    chainVestDesc: 'A sturdy vest with high DEF',
    metalCage: 'Metal Cage',
    metalCageDesc: 'It\'s not sexy, but it\'s effective',
    titaniumPlateSuit: 'Titanium Plate Suit',
    metalCageDesc: 'It\'s sexy and effective',
  },
  items: {
    goldPurse: 'Gold Purse',
    goldPurseDesc: 'Increases gold found by 15%',
    goldSack: 'Gold Sack',
    goldSackDesc: 'Increases gold found by 25%',
    magnifyingGlass: 'Magnifying Glass',
    magnifyingGlassDesc: 'Increases chance of finding rare loot by 15%',
    topHat: 'Top Hat',
    topHatDesc: 'This classy hat slightly protects the head and increases your chance to steal',
    gasMask: 'Gas Mask',
    gasMaskDesc: 'Protects against poison and can intimidate enemies',
    metalGloves: 'Metal Gloves',
    metalGlovesDesc: 'Increases defense, but terrible for stealing',
    codPiece: 'Cod Piece',
    codPieceDesc: 'An effective, and a little intimidating, peice of protective crotch wear',
    metalBra: 'Metal Bra',
    metalBraDesc: 'A solid metal bra to add protection to sensitive bits. Can be intimidating for some enemies',
    steelToeBoots: 'Steel Toe Boots',
    steelToeBootsDesc: 'These classy boots increase crit chance and DEF',
    beer: 'Beer',
    beerDesc: 'Embews holder with courage to protect comrades',
    wine: 'Wine',
    wineDesc: 'Holder may spout heroic nonsense, inspiring comrades',
    whiskey: 'Whiskey',
    whiskeyDesc: 'This powerful drink causes you to protect and inspire teammates, but reduces crit chance and SCI DEF',
    absenth: 'Absenth',
    absenthDesc: 'Holder can see beyond the pale, increasing chance of finding rare items. Also makes you impervious to intimidation',
    scotch: 'One Hundred Year Old Scotch',
    scotchDesc: 'A drink so good it increases most stats'
  },


}

export default Strings;
